### ISSUE TITLE
The engine panics during analysis when multithreading is used

### ISSUE THREAD

**Issue by marmistrz** [fabianvdW/FabChess#27] opened 2020-02-27 07:29 UTC
To reproduce:
```
uci
setoption name Threads value 8
position fen 5rk1/1pP2pp1/p6p/8/3p4/P2P4/1P3PPP/5RK1 b - - 0 24
go depth 10
```
The issue doesn't occur if only one thread is used.

Log:
```
info depth 1 seldepth 0 nodes 0 nps 0 hashfull 0 time 0 score cp -199 pv f8c8 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 1 score cp -353 pv f8c8 f1c1 g8f8 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 1 score cp -353 pv f8c8 f1c1 g8f8 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 1 score cp -333 pv g8h7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 1 score cp -353 pv f8c8 f1c1 g8f8 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 1 score cp -353 pv f8c8 f1c1 g8f8 
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -199 pv f8c8 f1c1 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -333 pv g8h7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -333 pv g8h7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -323 pv h6h5 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -273 pv f7f6 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -333 pv g8h7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -323 pv h6h5 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -323 pv h6h5 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -273 pv f7f6 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -323 pv h6h5 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -273 pv f7f6 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -273 pv f7f6 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 4 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 4 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 4 score cp -320 pv f7f6 f1c1 g8f7 
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 5 score cp -320 pv f7f6 f1c1 g8f7 
info depth 4 seldepth 0 nodes 0 nps 0 hashfull 0 time 5 score cp -199 pv f8c8 f1c1 g8f8 h2h3 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 6 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 7 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 7 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 7 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 7 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 7 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 7 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 8 score cp -361 pv f7f6 f1c1 f8c8 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 9 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 9 score cp -361 pv f7f6 f1c1 f8c8 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 9 score cp -361 pv f7f6 f1c1 f8c8 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 10 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 10 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 10 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 11 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 11 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 11 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 12 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 12 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 13 score cp -361 pv f7f6 f1c1 f8c8 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 13 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 13 score cp -361 pv f7f6 f1c1 f8c8 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 13 score cp -361 pv f7f6 f1c1 f8c8 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 14 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 14 score cp -361 pv f7f6 f1c1 f8c8 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 14 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 15 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 15 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 16 score cp -304 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 17 score cp -273 pv f7f6 
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 17 score cp -199 pv f8c8 f1c1 g8f8 h2h3 f8e7 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 17 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 18 score cp -273 pv f7f6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 18 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 18 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 18 score cp -273 pv f7f6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 19 score cp -273 pv f7f6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 21 score cp -361 pv f7f6 f1c1 f8c8 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 21 score cp -361 pv f7f6 f1c1 f8c8 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 22 score cp -361 pv f7f6 f1c1 f8c8 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 23 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 23 score cp -273 pv f7f6 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 23 score cp -271 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 23 score cp -271 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 24 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 24 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 25 score cp -361 pv f7f6 f1c1 f8c8 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 25 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 26 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 27 score cp -273 pv f7f6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 27 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 27 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 27 score cp -273 pv f7f6 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 28 score cp -271 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 28 score cp -280 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 28 score cp -361 pv f7f6 f1c1 f8c8 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 28 score cp -273 pv f7f6 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 29 score cp -271 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 29 score cp -361 pv f7f6 f1c1 f8c8 
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 30 score cp -199 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 31 score cp -271 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 31 score cp -271 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 34 score cp -271 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 34 score cp -221 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1e1 e7d6 g1h1 
info depth 8 seldepth 0 nodes 0 nps 0 hashfull 0 time 36 score cp -199 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 c4d4 d6c7 
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 38 score cp -167 pv f8c8 f1c1 g8f8 g2g4 
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 43 score cp -165 pv f8c8 f1c1 g8f8 c1c4 
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 51 score cp -160 pv f8c8 f1c1 g8f8 c1c4 f8e7 h2h3 e7d6 c4d4 d6c7 d4c4 c7b8 
info depth 10 seldepth 13 nodes 7133 nps 118883 hashfull 0 time 60 score cp -181 pv f8c8 f1c1 g8f8 h2h3 f8e7 c1c4 e7d6 c4d4 d6c7 d4c4 c7b8 g1f1 
info depth 10 seldepth 13 nodes 7133 nps 113222 hashfull 0 time 63 score cp -162 pv f8c8 f1c1 g8f8 c1c4 f8e8 g2g4 e8d7 c4d4 d7c7 d4c4 c7b8 g4g5 
thread '<unnamed>' panicked at 'assertion failed: !move_orderer.has_legal_move || current_max_score > STANDARD_SCORE', src/search/alphabeta.rs:336:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'assertion failed: !move_orderer.has_legal_move || current_max_score > STANDARD_SCORE', src/search/alphabeta.rs:336:5
thread '<unnamed>' panicked at 'assertion failed: !move_orderer.has_legal_move || current_max_score > STANDARD_SCORE', src/search/alphabeta.rs:336:5
thread '<unnamed>' panicked at 'assertion failed: !move_orderer.has_legal_move || current_max_score > STANDARD_SCORE', src/search/alphabeta.rs:336:5
```

**Comment by fabianvdW** [comment] 2020-02-27 10:37
Thanks for your report, I sadly couldn't reproduce it with the 4 threads I have on current master. Can you tell me which version you are using, and if you are using a debug or release compile? 

```
go infinite
info depth 1 seldepth 0 nodes 0 nps 0 hashfull 0 time 0 score cp -351 pv g8h7
info depth 1 seldepth 0 nodes 0 nps 0 hashfull 0 time 0 score cp -350 pv h6h5
info depth 1 seldepth 0 nodes 0 nps 0 hashfull 0 time 0 score cp -320 pv f8e8
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 0 score cp -1697 pv f8e8 c
7c8q
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 0 score cp -1690 pv a6a5 c
7c8q
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 1 score cp -1688 pv b7b5 c
7c8q
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 1 score cp -352 pv f8a8 f2
f3
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -1690 pv a6a5 c
7c8q
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 2 score cp -1688 pv b7b5 c
7c8q
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -382 pv f8a8 f1
c1
info depth 2 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -376 pv f8c8 f1
c1
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -354 pv g8h7 f1
e1 h7g6
info depth 3 seldepth 0 nodes 0 nps 0 hashfull 0 time 3 score cp -353 pv f8c8 f1
c1 g8f8
info depth 4 seldepth 0 nodes 0 nps 0 hashfull 0 time 4 score cp -356 pv f8c8 f1
c1 g8f8 g1f1
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 4 score cp -317 pv f8c8 f1
c1 g8f8 h2h4 f8e7
info depth 5 seldepth 0 nodes 0 nps 0 hashfull 0 time 4 score cp -315 pv f8c8 f1
c1 g8f8 c1c5 f8e7
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 5 score cp -333 pv f8c8 f1
c1 g8f8 g1f1 f8e7 f1e2
info depth 6 seldepth 0 nodes 0 nps 0 hashfull 0 time 5 score cp -316 pv f8c8 f1
c1 g8f8 f2f3 f8e7 g1f2
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 5 score cp -342 pv f8e8 f1
c1 g7g6
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 6 score cp -316 pv f8c8 f1
c1 g8f8 f2f3 f8e7 g1f2 e7d6
info depth 7 seldepth 0 nodes 0 nps 0 hashfull 0 time 6 score cp -300 pv f8c8 f1
c1 g8f8 g2g4
info depth 8 seldepth 0 nodes 0 nps 0 hashfull 0 time 9 score cp -296 pv f8c8 f1
c1 g8f8 f2f3 f8e7 g1f2 e7d6 f2e2
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 10 score cp -310 pv f8c8 f
1c1 g8f8 h2h3 f8e7 c1c5
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 10 score cp -293 pv f8c8 f
1c1 g8f8 h2h3 f8e7 f2f4 e7d6 g1f2
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 10 score cp -276 pv f8c8 f
1c1 g8f8 f2f3 f8e7 h2h3 e7d6 g1h2
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 11 score cp -263 pv f8c8 f
1c1 g8f8 h2h3 f8e7 g2g3 e7d6 c1c5
info depth 9 seldepth 0 nodes 0 nps 0 hashfull 0 time 12 score cp -258 pv f8c8 f
1c1 g8f8 g2g3 f8e7 b2b4
info depth 9 seldepth 13 nodes 8192 nps 630153 hashfull 0 time 13 score cp -218
pv f8c8 f1c1 g8f8 h2h3 f8e7 b2b3 e7d6 c1b1
info depth 9 seldepth 13 nodes 8192 nps 630153 hashfull 0 time 13 score cp -188
pv f8c8 f1c1 g8f8 g2g4 f8e7 g1h1 e7d6 c1a1
info depth 9 seldepth 13 nodes 8192 nps 585142 hashfull 0 time 14 score cp -162
pv f8c8 f1c1 g8f8 h2h4 f8e7 b2b4 e7d6 b4b5 a6b5
info depth 9 seldepth 13 nodes 8192 nps 585142 hashfull 0 time 14 score cp -156
pv f8c8 f1c1 g8f8 g2g4 f8e7 g4g5 h6g5 g1g2 e7d6
info depth 10 seldepth 13 nodes 16384 nps 1092266 hashfull 0 time 15 score cp -1
56 pv f8c8 f1c1 g8f8 b2b4 f8e7 b4b5 a6b5 g2g4 e7d6
info depth 10 seldepth 15 nodes 24576 nps 1536000 hashfull 0 time 16 score cp -1
55 pv f8c8 f1c1 g8f8 g1f1 f8e7 c1c4 e7d6 c4d4 d6c7 d4e4 c7d8
info depth 10 seldepth 15 nodes 24576 nps 1536000 hashfull 0 time 16 score cp -1
49 pv f8c8 f1c1 g8f8 g1f1 f8e7 c1c4 e7d6 c4d4 d6c7 d4c4 c7b8 c4c8 b8c8
info depth 11 seldepth 15 nodes 24576 nps 1365333 hashfull 0 time 18 score cp -1
68 pv f8c8 f1c1 g8f8 g1f1 f8e7 c1c4 e7d6 c4d4 d6c7 d4c4 c7b8 c4c8 b8c8 f1e2
info depth 12 seldepth 18 nodes 73728 nps 2949120 hashfull 0 time 25 score cp -1
38 pv f8c8 f1c1 g8f8 g1f1 f8e7 f1e2 e7d7 c1c4 c8c7 c4d4 d7e6 h2h4 c7c6
info depth 13 seldepth 18 nodes 73728 nps 2949120 hashfull 0 time 25 score cp -1
51 pv f8c8 f1c1 g8f8 c1c4 f8e7 h2h3
info depth 13 seldepth 18 nodes 90112 nps 3218285 hashfull 0 time 28 score cp -1
34 pv f8c8 f1c1 g8f8 c1c4 f8e7 b2b3 e7d6 c4d4 d6c7 d4c4 c7d8 b3b4
info depth 14 seldepth 18 nodes 131072 nps 3744914 hashfull 0 time 35 score cp -
118 pv f8c8 f1c1 g8f8 b2b4 f8e7 b4b5 a6b5 h2h4 e7d6 c1a1
info depth 14 seldepth 20 nodes 172032 nps 4411076 hashfull 0 time 39 score cp -
116 pv f8c8 f1c1 g8f8 g1f1 f8e7 f1e2 e7d7 c1c4 c8c7 c4d4 d7e6 b2b4
info depth 15 seldepth 21 nodes 245760 nps 4726153 hashfull 0 time 52 score cp -
124 pv f8c8 f1c1 g8f8 g2g3 f8e7 c1c4 b7b5 c4c6 e7d7 c6a6 c8c7 a6b6 c7c2
info depth 15 seldepth 21 nodes 253952 nps 4791547 hashfull 0 time 53 score cp -
119 pv f8c8 f1c1 g8f8 c1c4 f8e7 g2g3 b7b5 c4c6 e7d7 c6a6 c8c7 a6b6 c7c1 g1g2 c1c
5 g2f3
info depth 16 seldepth 22 nodes 311296 nps 4941206 hashfull 0 time 63 score cp -
128 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4d4 b7b
5 b2b4 f7f6
info depth 17 seldepth 23 nodes 376832 nps 5307492 hashfull 0 time 71 score cp -
133 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4d4 a6a
5 a3a4 f7f6 d4e4
info depth 18 seldepth 27 nodes 557056 nps 5742845 hashfull 0 time 97 score cp -
140 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4d4 f7f
6 h2h4 a6a5 a3a4 h6h5
info depth 19 seldepth 27 nodes 778240 nps 6080000 hashfull 0 time 128 score cp
-136 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7c6 e4d4 a6
a5 h2h4 a5a4 h4h5 c6d6 d4e4
info depth 20 seldepth 28 nodes 1024000 nps 6206060 hashfull 0 time 165 score cp
 -138 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7c6 e4d4 a
6a5 b2b4 a5b4 a3b4 c6b5 d4c3 f7f6
info depth 21 seldepth 29 nodes 1523712 nps 6322456 hashfull 8 time 241 score cp
 -139 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4d4 a
6a5 b2b4 a5a4 h2h4 h6h5 d4e4 f7f6 b4b5
info depth 22 seldepth 29 nodes 2351104 nps 6622828 hashfull 8 time 355 score cp
 -146 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4d4 b
7b5 b2b4 h6h5 d4e4 d6e6 h2h3 f7f5 e4f4 g7g6 h3h4
info depth 23 seldepth 33 nodes 3678208 nps 6761411 hashfull 34 time 544 score c
p -146 pv f8c8 f1c1 g8f8 g2g3 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4d4
b7b5 b2b4 g7g6 d4e4 h6h5 h2h3 d6e6 h3h4 e6d6 d3d4
info depth 24 seldepth 36 nodes 11665408 nps 6696560 hashfull 159 time 1742 scor
e cp -155 pv f8c8 f1c1 g8f8 g2g4 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4
d4 g7g6 a3a4 h6h5 g4h5 g6h5 a4a5 h5h4 h2h3 d6e6 d4e4 f7f5 e4e3
info depth 25 seldepth 37 nodes 18685952 nps 6642713 hashfull 255 time 2813 scor
e cp -149 pv f8c8 f1c1 g8f8 g2g4 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4
d4 g7g6 a3a4 h6h5 g4h5 g6h5 h2h4 a6a5 d4c4 d6e5 d3d4 e5d6 d4d5 f7f6
info depth 26 seldepth 37 nodes 23732224 nps 6500198 hashfull 316 time 3651 scor
e cp -149 pv f8c8 f1c1 g8f8 g2g4 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e4
d4 g7g6 a3a4 h6h5 g4h5 g6h5 h2h4 a6a5 d4c4 d6e5 d3d4 e5d6 d4d5 f7f6 c4d4
info depth 28 seldepth 40 nodes 72908800 nps 6297728 hashfull 807 time 11577 sco
re cp -154 pv f8c8 f1c1 g8f8 g2g4 f8e7 g1g2 e7d7 g2f3 c8c7 c1c7 d7c7 f3e4 c7d6 e
4d4 g7g6 a3a4 h6h5 g4h5 g6h5 h2h4 a6a5 d4c4 d6c6 d3d4 f7f6 f2f4 f6f5 b2b3 c6d6
info depth 29 seldepth 42 nodes 222568448 nps 6305769 hashfull 995 time 35296 sc
ore cp -162 pv f8c8 f1c1 h6h5 h2h4 g8f8 g1h2 f8e7 h2g3 e7d6 g3f4 c8c7 c1c7 d6c7
f4e5 c7c6 e5d4 a6a5 d4e5 a5a4 d3d4 c6d7 e5d5 b7b6 f2f3 f7f6 f3f4 g7g6 g2g3 d7e7

info depth 30 seldepth 42 nodes 245522432 nps 6300940 hashfull 998 time 38966 sc
ore cp -166 pv f8c8 f1c1 h6h5 h2h4 g8f8 g1h2 f8e7 h2g3 e7d7 g3f4 c8c7 c1c7 d7c7
f4e5 c7c6 e5d4 c6d6 a3a4 b7b6 b2b4 a6a5 d4c4 d6c6 b4a5 b6a5 d3d4 f7f5 d4d5 c6d6
g2g3 g7g6 c4d4
```
Fabi

**Comment by marmistrz** [comment] 2020-02-27 11:00
I'm using current master, Rust stable, crate built as `cargo build --bin fabchess` (the main binary doesn't actually require nightly)

**Comment by fabianvdW** [comment] 2020-02-27 11:05
Right, only the benchmarks need nightly. Just a quick note, you are running in debug mode, if you want a faster compile use `cargo build --release --bin fabchess ` and for an even faster compile
`cargo rustc --release --bin fabchess -- -C target-cpu=native`.

I could reproduce now on master, before I was actually on another branch. Thanks, I will look into it.

**Comment by fabianvdW** [comment] 2020-02-27 11:15
Ah right, this error already caught my eye a while earlier, and I fixed it on the dev (timecontrol branch). I just pushed a fix to master aswell, thanks.

**Comment by fabianvdW** [comment] 2020-03-12 15:41
@marmistrz Is the issue resolved?  Closing this for now...

**Closed by fabianvdW** 2020-03-12 15:41 UTC

**Comment by marmistrz** [comment] 2020-03-12 17:12
Yes, the issue is fixed, thanks.
